version: '3'
services:
    postgres:
      restart: always
      image: postgres:latest
      ports:
        - "5432:${DB_PORT}"
      volumes:
        - .:/data/
        - ./postgres/dumps:/dumps
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_PORT}
